services:
  webhook-processor:
    build: .
    container_name: shopify-webhook-processor
    restart: always
    ports:
      - "3003:3003"
    env_file:
      - .env
    networks:
      - shared-services-network
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: shopify-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - shared-services-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

      
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - shared-services-network
    command: tunnel run
    environment:
      TUNNEL_TOKEN: eyJhIjoiZDNlMzE1NmY4ZGQwYWM1MDY3YjcyZDQzNTVhMGNlMWIiLCJ0IjoiNTQwNWIyOGEtZWZjOS00MWIwLTk1YTUtODIwYzQwMzliMTM4IiwicyI6IlpXVm1NbVJtTVdNdFlqZzBNQzAwTkdaaExUbGtaVEl0TURjMk0yRTBNR013TW1RMSJ9

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: syncuser
      POSTGRES_PASSWORD: syncpass
      POSTGRES_DB: syncdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-services-network

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - shared-services-network



networks:
  shared-services-network:
    external: true

volumes:
  rabbitmq_data: {}
  postgres_data: {}
